[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_swap = "D5Lb79jeod4q5QdFYGUmdf3dkDkNuuVB6oZhWNJbpg3H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/ashutosh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
