[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_swap = "2DPfwhdg1K1zZFnY9fg4YQXmqB5ifAFXwU7x3KrXTg4o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/ashutosh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
